disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Bento Friday"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "A site celebrating all the bentos made for Bento Friday for my wife and her co-workers."
logo = "logo.png"

["params.author"]
name = "Bento by Metal Slime"
image = "chibi_me.jpg"
